### PR TITLE
Issue #18 - Fix the mobile navbar

### PR DESCRIPTION
**Pull request by ij2002**
Fixed! I have also readjusted the h1 text on the beginning of the site for seamless responsiveness

### **Navbar**

_Before:_
https://github.com/user-attachments/assets/99a7978f-0ff3-45d3-8e66-75ce1797e801

_After:_
https://github.com/user-attachments/assets/ec562f21-fbcc-432a-90e6-bf0221d2ad2e

### **Responsiveness**

_Before:_
image

_After:_
Screenshot 2024-08-12 170506

### CODE REVIEW

**Comment by djoufson** [comment]
Hello @ij2002 did you try the navbar responsive on mobile? I mean the initial problem was that when scrolling till a certain point, the navbar behavior was broken. The toggle stops working. Did you check that? I would like to see some screenshots please

**Comment by djoufson** [comment]
By the way, thanks for contributing

**Comment by ij2002** [comment]
> Hello @ij2002 did you try the navbar responsive on mobile? I mean the initial problem was that when scrolling till a certain point, the navbar behavior was broken. The toggle stops working. Did you check that? I would like to see some screenshots please

Hello! Yes, I have, I've linked a video where I tested it on phone resolution and I'll link it below here again! And I'll link a few screenshots below as well

https://github.com/user-attachments/assets/ec562f21-fbcc-432a-90e6-bf0221d2ad2e

Screenshot 2024-08-13 015127
Screenshot 2024-08-13 015141

**Comment by djoufson** [comment]
Looks great!!!!

**Review by djoufson — APPROVED** [review]

**Comment by djoufson** [comment]
By the way @ij2002 , if you have a better proposition for the navbar even a Figma design, a screenshot or something like that, submit that in this thread so that we have a preview of how it will look like before we implement anything. Take in consideration the overall design guidelines (colors, typography, sizes ...)

**Comment by ij2002** [comment]
> By the way @ij2002 , if you have a better proposition for the navbar even a Figma design, a screenshot or something like that, submit that in this thread so that we have a preview of how it will look like before we implement anything. Take in consideration the overall design guidelines (colors, typography, sizes ...)

Amazing! I shall play around with the elements during the week and update a design idea on here. If your team has a current Figma, I could try it there too using a copy of the Figma or on the Figma itself.

**Comment by djoufson** [comment]
I will open some other issues tomorrow, I have some bugs to fix before. There is still the about page to develop and the footer links to fix, maybe you can help there

**Comment by ij2002** [comment]
For sure! I'll look into the issues when added!

**Pull request merged**
